/**
 * generated by Xtext 2.9.2
 */
package at.ac.tuwien.big.leveldesign.scoping;

import at.ac.tuwien.big.leveldesign.scoping.AbstractLevelDesignScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
@SuppressWarnings("all")
public class LevelDesignScopeProvider extends AbstractLevelDesignScopeProvider {
}
