/*
 * generated by Xtext 2.9.2
 */
package at.ac.tuwien.big.leveldesign


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class LevelDesignRuntimeModule extends AbstractLevelDesignRuntimeModule {
}
