/*
 * generated by Xtext 2.9.2
 */
package at.ac.tuwien.big.leveldesign


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class LevelDesignStandaloneSetup extends LevelDesignStandaloneSetupGenerated {

	def static void doSetup() {
		new LevelDesignStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
