/**
 * generated by Xtext 2.9.2
 */
package at.ac.tuwien.big.leveldesign.ui.contentassist;

import at.ac.tuwien.big.leveldesign.ui.contentassist.AbstractLevelDesignProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class LevelDesignProposalProvider extends AbstractLevelDesignProposalProvider {
}
