/*
 * generated by Xtext 2.10.0
 */
package at.ac.tuwien.big.leveldesign.ui;

import at.ac.tuwien.big.leveldesign.ui.internal.LeveldesignActivator;
import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class LevelDesignExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return LeveldesignActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return LeveldesignActivator.getInstance().getInjector(LeveldesignActivator.AT_AC_TUWIEN_BIG_LEVELDESIGN_LEVELDESIGN);
	}
	
}
