/**
 * generated by Xtext 2.9.2
 */
package at.ac.tuwien.big.leveldesign;

import at.ac.tuwien.big.leveldesign.AbstractLevelDesignRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class LevelDesignRuntimeModule extends AbstractLevelDesignRuntimeModule {
}
