/**
 * generated by Xtext 2.9.2
 */
package at.ac.tuwien.big.leveldesign.ui;

import at.ac.tuwien.big.leveldesign.ui.AbstractLevelDesignUiModule;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class LevelDesignUiModule extends AbstractLevelDesignUiModule {
  public LevelDesignUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
