/**
 * generated by Xtext 2.9.2
 */
package at.ac.tuwien.big.leveldesign.validation;

import at.ac.tuwien.big.leveldesign.validation.AbstractLevelDesignValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class LevelDesignValidator extends AbstractLevelDesignValidator {
}
