/*
 * generated by Xtext 2.10.0
 */
package at.ac.tuwien.big.leveldesign.parser.antlr;

import at.ac.tuwien.big.leveldesign.parser.antlr.internal.InternalLevelDesignParser;
import at.ac.tuwien.big.leveldesign.services.LevelDesignGrammarAccess;
import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class LevelDesignParser extends AbstractAntlrParser {

	@Inject
	private LevelDesignGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalLevelDesignParser createParser(XtextTokenStream stream) {
		return new InternalLevelDesignParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Level";
	}

	public LevelDesignGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(LevelDesignGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
