/*
 * generated by Xtext 2.10.0
 */
package at.ac.tuwien.big.leveldesign.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class LevelDesignAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("at/ac/tuwien/big/leveldesign/parser/antlr/internal/InternalLevelDesign.tokens");
	}
}
