/**
 * generated by Xtext 2.10.0
 */
package at.ac.tuwien.big.leveldesign.levelDesign;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see at.ac.tuwien.big.leveldesign.levelDesign.LevelDesignFactory
 * @model kind="package"
 * @generated
 */
public interface LevelDesignPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "levelDesign";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.ac.at/tuwien/big/leveldesign/LevelDesign";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "levelDesign";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  LevelDesignPackage eINSTANCE = at.ac.tuwien.big.leveldesign.levelDesign.impl.LevelDesignPackageImpl.init();

  /**
   * The meta object id for the '{@link at.ac.tuwien.big.leveldesign.levelDesign.impl.LevelImpl <em>Level</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see at.ac.tuwien.big.leveldesign.levelDesign.impl.LevelImpl
   * @see at.ac.tuwien.big.leveldesign.levelDesign.impl.LevelDesignPackageImpl#getLevel()
   * @generated
   */
  int LEVEL = 0;

  /**
   * The feature id for the '<em><b>Spawn Room</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LEVEL__SPAWN_ROOM = 0;

  /**
   * The feature id for the '<em><b>Goal Room</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LEVEL__GOAL_ROOM = 1;

  /**
   * The feature id for the '<em><b>Rooms</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LEVEL__ROOMS = 2;

  /**
   * The number of structural features of the '<em>Level</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LEVEL_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link at.ac.tuwien.big.leveldesign.levelDesign.impl.RoomImpl <em>Room</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see at.ac.tuwien.big.leveldesign.levelDesign.impl.RoomImpl
   * @see at.ac.tuwien.big.leveldesign.levelDesign.impl.LevelDesignPackageImpl#getRoom()
   * @generated
   */
  int ROOM = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROOM__NAME = 0;

  /**
   * The feature id for the '<em><b>Columns</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROOM__COLUMNS = 1;

  /**
   * The feature id for the '<em><b>Rows</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROOM__ROWS = 2;

  /**
   * The feature id for the '<em><b>Entry</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROOM__ENTRY = 3;

  /**
   * The feature id for the '<em><b>Exit</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROOM__EXIT = 4;

  /**
   * The feature id for the '<em><b>Exit Connection</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROOM__EXIT_CONNECTION = 5;

  /**
   * The feature id for the '<em><b>Walls</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROOM__WALLS = 6;

  /**
   * The feature id for the '<em><b>Trapdoors</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROOM__TRAPDOORS = 7;

  /**
   * The feature id for the '<em><b>Monsters</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROOM__MONSTERS = 8;

  /**
   * The number of structural features of the '<em>Room</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROOM_FEATURE_COUNT = 9;

  /**
   * The meta object id for the '{@link at.ac.tuwien.big.leveldesign.levelDesign.impl.ConnectionImpl <em>Connection</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see at.ac.tuwien.big.leveldesign.levelDesign.impl.ConnectionImpl
   * @see at.ac.tuwien.big.leveldesign.levelDesign.impl.LevelDesignPackageImpl#getConnection()
   * @generated
   */
  int CONNECTION = 2;

  /**
   * The feature id for the '<em><b>Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONNECTION__TYPE = 0;

  /**
   * The feature id for the '<em><b>Next Room</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONNECTION__NEXT_ROOM = 1;

  /**
   * The number of structural features of the '<em>Connection</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONNECTION_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link at.ac.tuwien.big.leveldesign.levelDesign.impl.MonsterImpl <em>Monster</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see at.ac.tuwien.big.leveldesign.levelDesign.impl.MonsterImpl
   * @see at.ac.tuwien.big.leveldesign.levelDesign.impl.LevelDesignPackageImpl#getMonster()
   * @generated
   */
  int MONSTER = 3;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MONSTER__NAME = 0;

  /**
   * The feature id for the '<em><b>Position</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MONSTER__POSITION = 1;

  /**
   * The feature id for the '<em><b>Hp</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MONSTER__HP = 2;

  /**
   * The feature id for the '<em><b>Damage</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MONSTER__DAMAGE = 3;

  /**
   * The feature id for the '<em><b>Speed</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MONSTER__SPEED = 4;

  /**
   * The feature id for the '<em><b>Range</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MONSTER__RANGE = 5;

  /**
   * The feature id for the '<em><b>Aggro Radius</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MONSTER__AGGRO_RADIUS = 6;

  /**
   * The number of structural features of the '<em>Monster</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MONSTER_FEATURE_COUNT = 7;

  /**
   * The meta object id for the '{@link at.ac.tuwien.big.leveldesign.levelDesign.impl.TrapdoorImpl <em>Trapdoor</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see at.ac.tuwien.big.leveldesign.levelDesign.impl.TrapdoorImpl
   * @see at.ac.tuwien.big.leveldesign.levelDesign.impl.LevelDesignPackageImpl#getTrapdoor()
   * @generated
   */
  int TRAPDOOR = 4;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRAPDOOR__NAME = 0;

  /**
   * The feature id for the '<em><b>Position</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRAPDOOR__POSITION = 1;

  /**
   * The number of structural features of the '<em>Trapdoor</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRAPDOOR_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link at.ac.tuwien.big.leveldesign.levelDesign.impl.WallImpl <em>Wall</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see at.ac.tuwien.big.leveldesign.levelDesign.impl.WallImpl
   * @see at.ac.tuwien.big.leveldesign.levelDesign.impl.LevelDesignPackageImpl#getWall()
   * @generated
   */
  int WALL = 5;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WALL__NAME = 0;

  /**
   * The feature id for the '<em><b>From</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WALL__FROM = 1;

  /**
   * The feature id for the '<em><b>To</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WALL__TO = 2;

  /**
   * The number of structural features of the '<em>Wall</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WALL_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link at.ac.tuwien.big.leveldesign.levelDesign.impl.EntryImpl <em>Entry</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see at.ac.tuwien.big.leveldesign.levelDesign.impl.EntryImpl
   * @see at.ac.tuwien.big.leveldesign.levelDesign.impl.LevelDesignPackageImpl#getEntry()
   * @generated
   */
  int ENTRY = 6;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENTRY__NAME = 0;

  /**
   * The feature id for the '<em><b>Position</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENTRY__POSITION = 1;

  /**
   * The number of structural features of the '<em>Entry</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENTRY_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link at.ac.tuwien.big.leveldesign.levelDesign.impl.ExitImpl <em>Exit</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see at.ac.tuwien.big.leveldesign.levelDesign.impl.ExitImpl
   * @see at.ac.tuwien.big.leveldesign.levelDesign.impl.LevelDesignPackageImpl#getExit()
   * @generated
   */
  int EXIT = 7;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXIT__NAME = 0;

  /**
   * The feature id for the '<em><b>Position</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXIT__POSITION = 1;

  /**
   * The number of structural features of the '<em>Exit</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXIT_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link at.ac.tuwien.big.leveldesign.levelDesign.impl.CoordinateImpl <em>Coordinate</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see at.ac.tuwien.big.leveldesign.levelDesign.impl.CoordinateImpl
   * @see at.ac.tuwien.big.leveldesign.levelDesign.impl.LevelDesignPackageImpl#getCoordinate()
   * @generated
   */
  int COORDINATE = 8;

  /**
   * The feature id for the '<em><b>Column</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COORDINATE__COLUMN = 0;

  /**
   * The feature id for the '<em><b>Row</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COORDINATE__ROW = 1;

  /**
   * The number of structural features of the '<em>Coordinate</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COORDINATE_FEATURE_COUNT = 2;


  /**
   * Returns the meta object for class '{@link at.ac.tuwien.big.leveldesign.levelDesign.Level <em>Level</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Level</em>'.
   * @see at.ac.tuwien.big.leveldesign.levelDesign.Level
   * @generated
   */
  EClass getLevel();

  /**
   * Returns the meta object for the reference '{@link at.ac.tuwien.big.leveldesign.levelDesign.Level#getSpawnRoom <em>Spawn Room</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Spawn Room</em>'.
   * @see at.ac.tuwien.big.leveldesign.levelDesign.Level#getSpawnRoom()
   * @see #getLevel()
   * @generated
   */
  EReference getLevel_SpawnRoom();

  /**
   * Returns the meta object for the reference '{@link at.ac.tuwien.big.leveldesign.levelDesign.Level#getGoalRoom <em>Goal Room</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Goal Room</em>'.
   * @see at.ac.tuwien.big.leveldesign.levelDesign.Level#getGoalRoom()
   * @see #getLevel()
   * @generated
   */
  EReference getLevel_GoalRoom();

  /**
   * Returns the meta object for the containment reference list '{@link at.ac.tuwien.big.leveldesign.levelDesign.Level#getRooms <em>Rooms</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Rooms</em>'.
   * @see at.ac.tuwien.big.leveldesign.levelDesign.Level#getRooms()
   * @see #getLevel()
   * @generated
   */
  EReference getLevel_Rooms();

  /**
   * Returns the meta object for class '{@link at.ac.tuwien.big.leveldesign.levelDesign.Room <em>Room</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Room</em>'.
   * @see at.ac.tuwien.big.leveldesign.levelDesign.Room
   * @generated
   */
  EClass getRoom();

  /**
   * Returns the meta object for the attribute '{@link at.ac.tuwien.big.leveldesign.levelDesign.Room#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see at.ac.tuwien.big.leveldesign.levelDesign.Room#getName()
   * @see #getRoom()
   * @generated
   */
  EAttribute getRoom_Name();

  /**
   * Returns the meta object for the attribute '{@link at.ac.tuwien.big.leveldesign.levelDesign.Room#getColumns <em>Columns</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Columns</em>'.
   * @see at.ac.tuwien.big.leveldesign.levelDesign.Room#getColumns()
   * @see #getRoom()
   * @generated
   */
  EAttribute getRoom_Columns();

  /**
   * Returns the meta object for the attribute '{@link at.ac.tuwien.big.leveldesign.levelDesign.Room#getRows <em>Rows</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Rows</em>'.
   * @see at.ac.tuwien.big.leveldesign.levelDesign.Room#getRows()
   * @see #getRoom()
   * @generated
   */
  EAttribute getRoom_Rows();

  /**
   * Returns the meta object for the containment reference '{@link at.ac.tuwien.big.leveldesign.levelDesign.Room#getEntry <em>Entry</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Entry</em>'.
   * @see at.ac.tuwien.big.leveldesign.levelDesign.Room#getEntry()
   * @see #getRoom()
   * @generated
   */
  EReference getRoom_Entry();

  /**
   * Returns the meta object for the containment reference '{@link at.ac.tuwien.big.leveldesign.levelDesign.Room#getExit <em>Exit</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Exit</em>'.
   * @see at.ac.tuwien.big.leveldesign.levelDesign.Room#getExit()
   * @see #getRoom()
   * @generated
   */
  EReference getRoom_Exit();

  /**
   * Returns the meta object for the containment reference '{@link at.ac.tuwien.big.leveldesign.levelDesign.Room#getExitConnection <em>Exit Connection</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Exit Connection</em>'.
   * @see at.ac.tuwien.big.leveldesign.levelDesign.Room#getExitConnection()
   * @see #getRoom()
   * @generated
   */
  EReference getRoom_ExitConnection();

  /**
   * Returns the meta object for the containment reference list '{@link at.ac.tuwien.big.leveldesign.levelDesign.Room#getWalls <em>Walls</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Walls</em>'.
   * @see at.ac.tuwien.big.leveldesign.levelDesign.Room#getWalls()
   * @see #getRoom()
   * @generated
   */
  EReference getRoom_Walls();

  /**
   * Returns the meta object for the containment reference list '{@link at.ac.tuwien.big.leveldesign.levelDesign.Room#getTrapdoors <em>Trapdoors</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Trapdoors</em>'.
   * @see at.ac.tuwien.big.leveldesign.levelDesign.Room#getTrapdoors()
   * @see #getRoom()
   * @generated
   */
  EReference getRoom_Trapdoors();

  /**
   * Returns the meta object for the containment reference list '{@link at.ac.tuwien.big.leveldesign.levelDesign.Room#getMonsters <em>Monsters</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Monsters</em>'.
   * @see at.ac.tuwien.big.leveldesign.levelDesign.Room#getMonsters()
   * @see #getRoom()
   * @generated
   */
  EReference getRoom_Monsters();

  /**
   * Returns the meta object for class '{@link at.ac.tuwien.big.leveldesign.levelDesign.Connection <em>Connection</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Connection</em>'.
   * @see at.ac.tuwien.big.leveldesign.levelDesign.Connection
   * @generated
   */
  EClass getConnection();

  /**
   * Returns the meta object for the attribute '{@link at.ac.tuwien.big.leveldesign.levelDesign.Connection#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Type</em>'.
   * @see at.ac.tuwien.big.leveldesign.levelDesign.Connection#getType()
   * @see #getConnection()
   * @generated
   */
  EAttribute getConnection_Type();

  /**
   * Returns the meta object for the reference '{@link at.ac.tuwien.big.leveldesign.levelDesign.Connection#getNextRoom <em>Next Room</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Next Room</em>'.
   * @see at.ac.tuwien.big.leveldesign.levelDesign.Connection#getNextRoom()
   * @see #getConnection()
   * @generated
   */
  EReference getConnection_NextRoom();

  /**
   * Returns the meta object for class '{@link at.ac.tuwien.big.leveldesign.levelDesign.Monster <em>Monster</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Monster</em>'.
   * @see at.ac.tuwien.big.leveldesign.levelDesign.Monster
   * @generated
   */
  EClass getMonster();

  /**
   * Returns the meta object for the attribute '{@link at.ac.tuwien.big.leveldesign.levelDesign.Monster#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see at.ac.tuwien.big.leveldesign.levelDesign.Monster#getName()
   * @see #getMonster()
   * @generated
   */
  EAttribute getMonster_Name();

  /**
   * Returns the meta object for the containment reference '{@link at.ac.tuwien.big.leveldesign.levelDesign.Monster#getPosition <em>Position</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Position</em>'.
   * @see at.ac.tuwien.big.leveldesign.levelDesign.Monster#getPosition()
   * @see #getMonster()
   * @generated
   */
  EReference getMonster_Position();

  /**
   * Returns the meta object for the attribute '{@link at.ac.tuwien.big.leveldesign.levelDesign.Monster#getHp <em>Hp</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Hp</em>'.
   * @see at.ac.tuwien.big.leveldesign.levelDesign.Monster#getHp()
   * @see #getMonster()
   * @generated
   */
  EAttribute getMonster_Hp();

  /**
   * Returns the meta object for the attribute '{@link at.ac.tuwien.big.leveldesign.levelDesign.Monster#getDamage <em>Damage</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Damage</em>'.
   * @see at.ac.tuwien.big.leveldesign.levelDesign.Monster#getDamage()
   * @see #getMonster()
   * @generated
   */
  EAttribute getMonster_Damage();

  /**
   * Returns the meta object for the attribute '{@link at.ac.tuwien.big.leveldesign.levelDesign.Monster#getSpeed <em>Speed</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Speed</em>'.
   * @see at.ac.tuwien.big.leveldesign.levelDesign.Monster#getSpeed()
   * @see #getMonster()
   * @generated
   */
  EAttribute getMonster_Speed();

  /**
   * Returns the meta object for the attribute '{@link at.ac.tuwien.big.leveldesign.levelDesign.Monster#getRange <em>Range</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Range</em>'.
   * @see at.ac.tuwien.big.leveldesign.levelDesign.Monster#getRange()
   * @see #getMonster()
   * @generated
   */
  EAttribute getMonster_Range();

  /**
   * Returns the meta object for the attribute '{@link at.ac.tuwien.big.leveldesign.levelDesign.Monster#getAggroRadius <em>Aggro Radius</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Aggro Radius</em>'.
   * @see at.ac.tuwien.big.leveldesign.levelDesign.Monster#getAggroRadius()
   * @see #getMonster()
   * @generated
   */
  EAttribute getMonster_AggroRadius();

  /**
   * Returns the meta object for class '{@link at.ac.tuwien.big.leveldesign.levelDesign.Trapdoor <em>Trapdoor</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Trapdoor</em>'.
   * @see at.ac.tuwien.big.leveldesign.levelDesign.Trapdoor
   * @generated
   */
  EClass getTrapdoor();

  /**
   * Returns the meta object for the attribute '{@link at.ac.tuwien.big.leveldesign.levelDesign.Trapdoor#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see at.ac.tuwien.big.leveldesign.levelDesign.Trapdoor#getName()
   * @see #getTrapdoor()
   * @generated
   */
  EAttribute getTrapdoor_Name();

  /**
   * Returns the meta object for the containment reference '{@link at.ac.tuwien.big.leveldesign.levelDesign.Trapdoor#getPosition <em>Position</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Position</em>'.
   * @see at.ac.tuwien.big.leveldesign.levelDesign.Trapdoor#getPosition()
   * @see #getTrapdoor()
   * @generated
   */
  EReference getTrapdoor_Position();

  /**
   * Returns the meta object for class '{@link at.ac.tuwien.big.leveldesign.levelDesign.Wall <em>Wall</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Wall</em>'.
   * @see at.ac.tuwien.big.leveldesign.levelDesign.Wall
   * @generated
   */
  EClass getWall();

  /**
   * Returns the meta object for the attribute '{@link at.ac.tuwien.big.leveldesign.levelDesign.Wall#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see at.ac.tuwien.big.leveldesign.levelDesign.Wall#getName()
   * @see #getWall()
   * @generated
   */
  EAttribute getWall_Name();

  /**
   * Returns the meta object for the containment reference '{@link at.ac.tuwien.big.leveldesign.levelDesign.Wall#getFrom <em>From</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>From</em>'.
   * @see at.ac.tuwien.big.leveldesign.levelDesign.Wall#getFrom()
   * @see #getWall()
   * @generated
   */
  EReference getWall_From();

  /**
   * Returns the meta object for the containment reference '{@link at.ac.tuwien.big.leveldesign.levelDesign.Wall#getTo <em>To</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>To</em>'.
   * @see at.ac.tuwien.big.leveldesign.levelDesign.Wall#getTo()
   * @see #getWall()
   * @generated
   */
  EReference getWall_To();

  /**
   * Returns the meta object for class '{@link at.ac.tuwien.big.leveldesign.levelDesign.Entry <em>Entry</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Entry</em>'.
   * @see at.ac.tuwien.big.leveldesign.levelDesign.Entry
   * @generated
   */
  EClass getEntry();

  /**
   * Returns the meta object for the attribute '{@link at.ac.tuwien.big.leveldesign.levelDesign.Entry#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see at.ac.tuwien.big.leveldesign.levelDesign.Entry#getName()
   * @see #getEntry()
   * @generated
   */
  EAttribute getEntry_Name();

  /**
   * Returns the meta object for the containment reference '{@link at.ac.tuwien.big.leveldesign.levelDesign.Entry#getPosition <em>Position</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Position</em>'.
   * @see at.ac.tuwien.big.leveldesign.levelDesign.Entry#getPosition()
   * @see #getEntry()
   * @generated
   */
  EReference getEntry_Position();

  /**
   * Returns the meta object for class '{@link at.ac.tuwien.big.leveldesign.levelDesign.Exit <em>Exit</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Exit</em>'.
   * @see at.ac.tuwien.big.leveldesign.levelDesign.Exit
   * @generated
   */
  EClass getExit();

  /**
   * Returns the meta object for the attribute '{@link at.ac.tuwien.big.leveldesign.levelDesign.Exit#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see at.ac.tuwien.big.leveldesign.levelDesign.Exit#getName()
   * @see #getExit()
   * @generated
   */
  EAttribute getExit_Name();

  /**
   * Returns the meta object for the containment reference '{@link at.ac.tuwien.big.leveldesign.levelDesign.Exit#getPosition <em>Position</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Position</em>'.
   * @see at.ac.tuwien.big.leveldesign.levelDesign.Exit#getPosition()
   * @see #getExit()
   * @generated
   */
  EReference getExit_Position();

  /**
   * Returns the meta object for class '{@link at.ac.tuwien.big.leveldesign.levelDesign.Coordinate <em>Coordinate</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Coordinate</em>'.
   * @see at.ac.tuwien.big.leveldesign.levelDesign.Coordinate
   * @generated
   */
  EClass getCoordinate();

  /**
   * Returns the meta object for the attribute '{@link at.ac.tuwien.big.leveldesign.levelDesign.Coordinate#getColumn <em>Column</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Column</em>'.
   * @see at.ac.tuwien.big.leveldesign.levelDesign.Coordinate#getColumn()
   * @see #getCoordinate()
   * @generated
   */
  EAttribute getCoordinate_Column();

  /**
   * Returns the meta object for the attribute '{@link at.ac.tuwien.big.leveldesign.levelDesign.Coordinate#getRow <em>Row</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Row</em>'.
   * @see at.ac.tuwien.big.leveldesign.levelDesign.Coordinate#getRow()
   * @see #getCoordinate()
   * @generated
   */
  EAttribute getCoordinate_Row();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  LevelDesignFactory getLevelDesignFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link at.ac.tuwien.big.leveldesign.levelDesign.impl.LevelImpl <em>Level</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see at.ac.tuwien.big.leveldesign.levelDesign.impl.LevelImpl
     * @see at.ac.tuwien.big.leveldesign.levelDesign.impl.LevelDesignPackageImpl#getLevel()
     * @generated
     */
    EClass LEVEL = eINSTANCE.getLevel();

    /**
     * The meta object literal for the '<em><b>Spawn Room</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LEVEL__SPAWN_ROOM = eINSTANCE.getLevel_SpawnRoom();

    /**
     * The meta object literal for the '<em><b>Goal Room</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LEVEL__GOAL_ROOM = eINSTANCE.getLevel_GoalRoom();

    /**
     * The meta object literal for the '<em><b>Rooms</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LEVEL__ROOMS = eINSTANCE.getLevel_Rooms();

    /**
     * The meta object literal for the '{@link at.ac.tuwien.big.leveldesign.levelDesign.impl.RoomImpl <em>Room</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see at.ac.tuwien.big.leveldesign.levelDesign.impl.RoomImpl
     * @see at.ac.tuwien.big.leveldesign.levelDesign.impl.LevelDesignPackageImpl#getRoom()
     * @generated
     */
    EClass ROOM = eINSTANCE.getRoom();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ROOM__NAME = eINSTANCE.getRoom_Name();

    /**
     * The meta object literal for the '<em><b>Columns</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ROOM__COLUMNS = eINSTANCE.getRoom_Columns();

    /**
     * The meta object literal for the '<em><b>Rows</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ROOM__ROWS = eINSTANCE.getRoom_Rows();

    /**
     * The meta object literal for the '<em><b>Entry</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ROOM__ENTRY = eINSTANCE.getRoom_Entry();

    /**
     * The meta object literal for the '<em><b>Exit</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ROOM__EXIT = eINSTANCE.getRoom_Exit();

    /**
     * The meta object literal for the '<em><b>Exit Connection</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ROOM__EXIT_CONNECTION = eINSTANCE.getRoom_ExitConnection();

    /**
     * The meta object literal for the '<em><b>Walls</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ROOM__WALLS = eINSTANCE.getRoom_Walls();

    /**
     * The meta object literal for the '<em><b>Trapdoors</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ROOM__TRAPDOORS = eINSTANCE.getRoom_Trapdoors();

    /**
     * The meta object literal for the '<em><b>Monsters</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ROOM__MONSTERS = eINSTANCE.getRoom_Monsters();

    /**
     * The meta object literal for the '{@link at.ac.tuwien.big.leveldesign.levelDesign.impl.ConnectionImpl <em>Connection</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see at.ac.tuwien.big.leveldesign.levelDesign.impl.ConnectionImpl
     * @see at.ac.tuwien.big.leveldesign.levelDesign.impl.LevelDesignPackageImpl#getConnection()
     * @generated
     */
    EClass CONNECTION = eINSTANCE.getConnection();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CONNECTION__TYPE = eINSTANCE.getConnection_Type();

    /**
     * The meta object literal for the '<em><b>Next Room</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CONNECTION__NEXT_ROOM = eINSTANCE.getConnection_NextRoom();

    /**
     * The meta object literal for the '{@link at.ac.tuwien.big.leveldesign.levelDesign.impl.MonsterImpl <em>Monster</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see at.ac.tuwien.big.leveldesign.levelDesign.impl.MonsterImpl
     * @see at.ac.tuwien.big.leveldesign.levelDesign.impl.LevelDesignPackageImpl#getMonster()
     * @generated
     */
    EClass MONSTER = eINSTANCE.getMonster();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MONSTER__NAME = eINSTANCE.getMonster_Name();

    /**
     * The meta object literal for the '<em><b>Position</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MONSTER__POSITION = eINSTANCE.getMonster_Position();

    /**
     * The meta object literal for the '<em><b>Hp</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MONSTER__HP = eINSTANCE.getMonster_Hp();

    /**
     * The meta object literal for the '<em><b>Damage</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MONSTER__DAMAGE = eINSTANCE.getMonster_Damage();

    /**
     * The meta object literal for the '<em><b>Speed</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MONSTER__SPEED = eINSTANCE.getMonster_Speed();

    /**
     * The meta object literal for the '<em><b>Range</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MONSTER__RANGE = eINSTANCE.getMonster_Range();

    /**
     * The meta object literal for the '<em><b>Aggro Radius</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MONSTER__AGGRO_RADIUS = eINSTANCE.getMonster_AggroRadius();

    /**
     * The meta object literal for the '{@link at.ac.tuwien.big.leveldesign.levelDesign.impl.TrapdoorImpl <em>Trapdoor</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see at.ac.tuwien.big.leveldesign.levelDesign.impl.TrapdoorImpl
     * @see at.ac.tuwien.big.leveldesign.levelDesign.impl.LevelDesignPackageImpl#getTrapdoor()
     * @generated
     */
    EClass TRAPDOOR = eINSTANCE.getTrapdoor();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TRAPDOOR__NAME = eINSTANCE.getTrapdoor_Name();

    /**
     * The meta object literal for the '<em><b>Position</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TRAPDOOR__POSITION = eINSTANCE.getTrapdoor_Position();

    /**
     * The meta object literal for the '{@link at.ac.tuwien.big.leveldesign.levelDesign.impl.WallImpl <em>Wall</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see at.ac.tuwien.big.leveldesign.levelDesign.impl.WallImpl
     * @see at.ac.tuwien.big.leveldesign.levelDesign.impl.LevelDesignPackageImpl#getWall()
     * @generated
     */
    EClass WALL = eINSTANCE.getWall();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute WALL__NAME = eINSTANCE.getWall_Name();

    /**
     * The meta object literal for the '<em><b>From</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference WALL__FROM = eINSTANCE.getWall_From();

    /**
     * The meta object literal for the '<em><b>To</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference WALL__TO = eINSTANCE.getWall_To();

    /**
     * The meta object literal for the '{@link at.ac.tuwien.big.leveldesign.levelDesign.impl.EntryImpl <em>Entry</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see at.ac.tuwien.big.leveldesign.levelDesign.impl.EntryImpl
     * @see at.ac.tuwien.big.leveldesign.levelDesign.impl.LevelDesignPackageImpl#getEntry()
     * @generated
     */
    EClass ENTRY = eINSTANCE.getEntry();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ENTRY__NAME = eINSTANCE.getEntry_Name();

    /**
     * The meta object literal for the '<em><b>Position</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ENTRY__POSITION = eINSTANCE.getEntry_Position();

    /**
     * The meta object literal for the '{@link at.ac.tuwien.big.leveldesign.levelDesign.impl.ExitImpl <em>Exit</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see at.ac.tuwien.big.leveldesign.levelDesign.impl.ExitImpl
     * @see at.ac.tuwien.big.leveldesign.levelDesign.impl.LevelDesignPackageImpl#getExit()
     * @generated
     */
    EClass EXIT = eINSTANCE.getExit();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EXIT__NAME = eINSTANCE.getExit_Name();

    /**
     * The meta object literal for the '<em><b>Position</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXIT__POSITION = eINSTANCE.getExit_Position();

    /**
     * The meta object literal for the '{@link at.ac.tuwien.big.leveldesign.levelDesign.impl.CoordinateImpl <em>Coordinate</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see at.ac.tuwien.big.leveldesign.levelDesign.impl.CoordinateImpl
     * @see at.ac.tuwien.big.leveldesign.levelDesign.impl.LevelDesignPackageImpl#getCoordinate()
     * @generated
     */
    EClass COORDINATE = eINSTANCE.getCoordinate();

    /**
     * The meta object literal for the '<em><b>Column</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COORDINATE__COLUMN = eINSTANCE.getCoordinate_Column();

    /**
     * The meta object literal for the '<em><b>Row</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COORDINATE__ROW = eINSTANCE.getCoordinate_Row();

  }

} //LevelDesignPackage
