/**
 * generated by Xtext 2.10.0
 */
package at.ac.tuwien.big.leveldesign.levelDesign;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Room</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link at.ac.tuwien.big.leveldesign.levelDesign.Room#getName <em>Name</em>}</li>
 *   <li>{@link at.ac.tuwien.big.leveldesign.levelDesign.Room#getColumns <em>Columns</em>}</li>
 *   <li>{@link at.ac.tuwien.big.leveldesign.levelDesign.Room#getRows <em>Rows</em>}</li>
 *   <li>{@link at.ac.tuwien.big.leveldesign.levelDesign.Room#getEntry <em>Entry</em>}</li>
 *   <li>{@link at.ac.tuwien.big.leveldesign.levelDesign.Room#getExit <em>Exit</em>}</li>
 *   <li>{@link at.ac.tuwien.big.leveldesign.levelDesign.Room#getExitConnection <em>Exit Connection</em>}</li>
 *   <li>{@link at.ac.tuwien.big.leveldesign.levelDesign.Room#getWalls <em>Walls</em>}</li>
 *   <li>{@link at.ac.tuwien.big.leveldesign.levelDesign.Room#getTrapdoors <em>Trapdoors</em>}</li>
 *   <li>{@link at.ac.tuwien.big.leveldesign.levelDesign.Room#getMonsters <em>Monsters</em>}</li>
 * </ul>
 *
 * @see at.ac.tuwien.big.leveldesign.levelDesign.LevelDesignPackage#getRoom()
 * @model
 * @generated
 */
public interface Room extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see at.ac.tuwien.big.leveldesign.levelDesign.LevelDesignPackage#getRoom_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link at.ac.tuwien.big.leveldesign.levelDesign.Room#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Columns</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Columns</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Columns</em>' attribute.
   * @see #setColumns(int)
   * @see at.ac.tuwien.big.leveldesign.levelDesign.LevelDesignPackage#getRoom_Columns()
   * @model
   * @generated
   */
  int getColumns();

  /**
   * Sets the value of the '{@link at.ac.tuwien.big.leveldesign.levelDesign.Room#getColumns <em>Columns</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Columns</em>' attribute.
   * @see #getColumns()
   * @generated
   */
  void setColumns(int value);

  /**
   * Returns the value of the '<em><b>Rows</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Rows</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Rows</em>' attribute.
   * @see #setRows(int)
   * @see at.ac.tuwien.big.leveldesign.levelDesign.LevelDesignPackage#getRoom_Rows()
   * @model
   * @generated
   */
  int getRows();

  /**
   * Sets the value of the '{@link at.ac.tuwien.big.leveldesign.levelDesign.Room#getRows <em>Rows</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Rows</em>' attribute.
   * @see #getRows()
   * @generated
   */
  void setRows(int value);

  /**
   * Returns the value of the '<em><b>Entry</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Entry</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Entry</em>' containment reference.
   * @see #setEntry(Entry)
   * @see at.ac.tuwien.big.leveldesign.levelDesign.LevelDesignPackage#getRoom_Entry()
   * @model containment="true"
   * @generated
   */
  Entry getEntry();

  /**
   * Sets the value of the '{@link at.ac.tuwien.big.leveldesign.levelDesign.Room#getEntry <em>Entry</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Entry</em>' containment reference.
   * @see #getEntry()
   * @generated
   */
  void setEntry(Entry value);

  /**
   * Returns the value of the '<em><b>Exit</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Exit</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Exit</em>' containment reference.
   * @see #setExit(Exit)
   * @see at.ac.tuwien.big.leveldesign.levelDesign.LevelDesignPackage#getRoom_Exit()
   * @model containment="true"
   * @generated
   */
  Exit getExit();

  /**
   * Sets the value of the '{@link at.ac.tuwien.big.leveldesign.levelDesign.Room#getExit <em>Exit</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Exit</em>' containment reference.
   * @see #getExit()
   * @generated
   */
  void setExit(Exit value);

  /**
   * Returns the value of the '<em><b>Exit Connection</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Exit Connection</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Exit Connection</em>' containment reference.
   * @see #setExitConnection(Connection)
   * @see at.ac.tuwien.big.leveldesign.levelDesign.LevelDesignPackage#getRoom_ExitConnection()
   * @model containment="true"
   * @generated
   */
  Connection getExitConnection();

  /**
   * Sets the value of the '{@link at.ac.tuwien.big.leveldesign.levelDesign.Room#getExitConnection <em>Exit Connection</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Exit Connection</em>' containment reference.
   * @see #getExitConnection()
   * @generated
   */
  void setExitConnection(Connection value);

  /**
   * Returns the value of the '<em><b>Walls</b></em>' containment reference list.
   * The list contents are of type {@link at.ac.tuwien.big.leveldesign.levelDesign.Wall}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Walls</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Walls</em>' containment reference list.
   * @see at.ac.tuwien.big.leveldesign.levelDesign.LevelDesignPackage#getRoom_Walls()
   * @model containment="true"
   * @generated
   */
  EList<Wall> getWalls();

  /**
   * Returns the value of the '<em><b>Trapdoors</b></em>' containment reference list.
   * The list contents are of type {@link at.ac.tuwien.big.leveldesign.levelDesign.Trapdoor}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Trapdoors</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Trapdoors</em>' containment reference list.
   * @see at.ac.tuwien.big.leveldesign.levelDesign.LevelDesignPackage#getRoom_Trapdoors()
   * @model containment="true"
   * @generated
   */
  EList<Trapdoor> getTrapdoors();

  /**
   * Returns the value of the '<em><b>Monsters</b></em>' containment reference list.
   * The list contents are of type {@link at.ac.tuwien.big.leveldesign.levelDesign.Monster}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Monsters</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Monsters</em>' containment reference list.
   * @see at.ac.tuwien.big.leveldesign.levelDesign.LevelDesignPackage#getRoom_Monsters()
   * @model containment="true"
   * @generated
   */
  EList<Monster> getMonsters();

} // Room
