/*
 * generated by Xtext 2.10.0
 */
package at.ac.tuwien.big.leveldesign.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractLevelDesignScopeProvider extends DelegatingScopeProvider {
}
